name: download_data
channels:
  - defaults
dependencies:
  - pip=20.3.3
  - pip:
      - wandb==0.10.21
      - omegaconf==2.0.6
      - pandas==1.2.3
      - pillow==8.1.2
      - scikit-learn==0.24.1
      - plotly==4.4.1
      - matplotlib==3.2.2