name: download_data
channels:
  - defaults
dependencies:
  - pip=20.3.3
  - pip:
      - wandb==0.10.21
      - hydra-joblib-launcher==1.1.2
      - requests==2.24.0
      - mlflow==1.30.1
      - hydra-core==1.0.6
